# Generated by Django 3.2.10 on 2021-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcontainer',
            name='task_args',
        ),
        migrations.AddField(
            model_name='taskcontainer',
            name='scene_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='taskcontainer',
            name='scene_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
