#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
  push:
    branches:
      - master #Use your own branch here (Might be staging or testing)
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Git clone on our repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        run: make login

      - name: Build Containers
        run: make build

      - name: Push Containers
        run: make push

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                docker service update --force --image phillipjensen/golemgrid-container-manager:${{ github.sha }} golemgrid-backend_container-manager-api
                docker service update --force --image phillipjensen/golemgrid-container-manager-celery:${{ github.sha }} golemgrid-backend_celery_container_manager
                docker service update --force --image phillipjensen/golemgrid-container-manager-celery-beat:${{ github.sha }} golemgrid-backend_celery_beat_container_manager
  
  